### ISSUE TITLE
Automatically dismiss other instances to avoid stacking

### ISSUE THREAD

**Issue by fabiosoft** [ondalabs/OLGhostAlertView#5]
it's not possibile to dismiss it programmatically, or better... before show next alert dismiss the previous so the messages are not confused.

**Comment by radutzan** [comment]
The `hide` instance method is public since commit [3a6d5d56ba](https://github.com/ondalabs/OLGhostAlertView/commit/3a6d5d56ba3ed944ed894974142f39febbd16cb8), you can use that to dismiss OLGAV programatically. It would be nice to automatically dismiss other instances of OLGAV to avoid stacking, we'll certainly consider implementing that in the future.

**Comment by fabiosoft** [comment]
oh yes! great! dismiss all stack before show more OLGAV would be amazing! thanks for your control :)
